### PR TITLE
Adding "The Iron Blog" example and "Surf & Paddle" Assignment

### PR DESCRIPTION
**Pull request by al-the-x**
* [ ] **The Iron Blog, Take 3** :clapper: 
   * [X] **Yak Shaving** (XXXXL)
      * [X] HTML5 Boilerplate
      * [X] branch, commit, push, PR
   * [ ] **Page Header (M)**
     * [ ] logo image
     * [ ] resizing big images
     * [ ] rounding square images
     * [ ] big image
   * [ ] **Page Footer (L)**
     * [ ] logo image
     * [ ] rounding square images
     * [ ] resizing big images
     * [ ] navigation links
     * [ ] all on one line
  * [ ] **2-column Layout (L)**
    * [ ] side column left, main column right
    * [ ] fixed width
    * [ ] liquid width (%)
  * [ ] **Article x3 (XL)**
    * [ ] title + permalink
    * [ ] byline
    * [ ] body copy
    * [ ] body images
    * [ ] share links
    * [ ] timestamp

### CODE REVIEW

**Comment by al-the-x** [comment]
### Priority by Pomodoro

* **Article**
    * [ ] title + permalink
    * [ ] byline
    * [ ] body copy
    * [ ] body images
* **2-column Layout**
    * [ ] side column left, main column right
    * [ ] fixed width
* **Page Header**
     * [ ] logo image
     * [ ] resizing big images
     * [ ] rounding square images
     * [ ] big image
* **Page Footer**
     * [ ] logo image
     * [ ] rounding square images
     * [ ] resizing big images
     * [ ] navigation links
     * [ ] all on one line
* **Article**
    * [ ] share links
    * [ ] timestamp

**Comment by carolinapowers** [comment]
:+1:

**Comment by sak55** [comment]
:+1:

**Comment by jaredstevick** [comment]
:+1:

**Comment by mfees** [comment]
:+1:

**Comment by TaylorFoster90** [comment]
im so happy for you :+1:

**Comment by eklemen** [comment]
:+1:

**Comment by adamkarb** [comment]
:+1:

**Comment by jgarcia99** [comment]
:+1:

**Comment by jrutishauser** [comment]
:beers:

**Pull request merged**
